"""empty message

Revision ID: 1c91b74e20a5
Revises: 1130ef19f77c
Create Date: 2020-04-17 10:30:51.208329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c91b74e20a5'
down_revision = '1130ef19f77c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('reserved_booked', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'reserved_booked')
    # ### end Alembic commands ###
