"""empty message

Revision ID: 2ff6f3de66dc
Revises: 1c91b74e20a5
Create Date: 2020-04-17 10:57:53.924963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ff6f3de66dc'
down_revision = '1c91b74e20a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('reserved', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'reserved')
    # ### end Alembic commands ###
