"""empty message

Revision ID: e504de0aef93
Revises: 7b940965d8e4
Create Date: 2020-04-17 01:33:19.607107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e504de0aef93'
down_revision = '7b940965d8e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant__tables', sa.Column('occupancy', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant__tables', 'occupancy')
    # ### end Alembic commands ###
